defaults: &defaults
  
  base_url: 'https://wack-a-doo.de'

  game_identifier: 'WACKADOO'
  scope: 'wackadoo'

  cookie_name: 'ge_remember_token'
  
development:
  <<: *defaults

  base_url: 'https://localhost'
  
test:
  <<: *defaults

staging:
  <<: *defaults

  base_url: 'https://test1.wack-a-doo.com'

  scope: 'wackadoo-testround3'
  
production:
  <<: *defaults

  scope: 'wackadoo-round3'
