defaults: &defaults
  
  base_url:             'https://wack-a-doo.de'
  game_server_base_url: 'https://wack-a-doo.de/game_server'

  game_identifier:      'WACKADOO'
  scope:                'wackadoo'

  cookie_name:          'ge_remember_token'

  recently_updated_interval:  60 #minutes
  
development:
  <<: *defaults

  base_url:             'https://localhost'
  game_server_base_url: 'https://localhost/game_server'

test:
  <<: *defaults

staging:
  <<: *defaults

  base_url:             'https://test1.wack-a-doo.com'
  game_server_base_url: 'https://test1.wack-a-doo.de/game_server'

  scope:                'wackadoo-testround3'
  
production:
  <<: *defaults

  game_server_base_url: 'https://gs05.wack-a-doo.de/game_server'

  scope:                'wackadoo-round5'
