defaults: &defaults
  
  base_url: 'https://wack-a-doo.de'

  jabber:
    debug:     true
    host:      jabber3.wack-a-doo.com
    muc:       conference.jabber3.wack-a-doo.com
    bot_jid:   service@jabber3.wack-a-doo.com
    password:  P5Dda5eZmvCLFTw2
    name:      service
    admin_jid: shadow-dragon@jabber3.wack-a-doo.com
  
  base_time_factor:                         60 # duration of a minute in seconds; can be used to speed-up all operations
  movement_duration:                        15 # base-time of a movement in minutes 
  ap_regeneration_duration:                180 # time needed to regenerate a single action point in minutes

  attack_protection_duration:              300 # time in seconds
  
  overrunnable_threshold:                   10 # factor which an army has to be bigger than its oppenent to overrun it
  
  like_regeneration_duration:              360 # time needed to regenerate one like resource in minutes
  like_regeneration_duration_platinum:     180 # time needed by a platinum user to regenerate one like resource in minutes

  dislike_regeneration_duration:          1440 # time needed to regenerate one like resource in minutes
  dislike_regeneration_duration_platinum:  720 # time needed by a platinum user to regenerate one like resource in minutes
  
  like_maximum_amount:                       4 # regeneration stops after this amount of likes is reached
  dislike_maximum_amount:                    1 # regeneration stops after this amount of dislikes is reached

  military_only_flag_destroyed_armies:   false #if true the field removed for destroyed armies will be set true instead of deleting them from the database after a battle
  military_only_flag_destroyed_battles:   true #if true the field removed for finished battles will be set true instead of deleting them from the database after the battle is done
  
  payment_provider_base_url: 'https://wack-a-doo.de/payment_provider'
  
  game_identifier: 'WACKADOO'
  scope: 'wackadoo'

  default_character_name: 'WackyUser'
  
  identity_provider_base_url: 'https://test1.wack-a-doo.com/identity_provider'
  
  settlement_recalc_probability:    0.01
  resource_pool_recalc_probability: 0.05
  character_recalc_probability:     0.2
  queue_speed_recalc_probability:   0.2
  
  cookie_name: 'gs_remember_token'  
  
  status_email_recipient: 'cron@5dlab.com'
  chargeback_email_recipient: 'chargeback@5dlab.com'
  sales_email_recipient: 'sales@5dlab.com'

  platinum_additional_construction_jobs : 3
  platinum_additional_training_jobs     : 3
  
  history_update_interval:    24 #hours
  player_deletion_interval:   16 #days
  message_deletion_intervall: 30 #days

  special_offer_interval:          5 #days
  special_offer_dialog_max_count:  100

  artifact_jump_probability:             0.1     # probability of artifact to jump after a won battle
  artifact_capture_probability_factor:   0.05    # probability factor of artifact to be captured by attacker after every battle round
  artifact_capture_disable_time: 24 #hours to disable artifact capture after settlement move

  moving_disable_time_after_region_takeover: 12 #hours to disable moving to region after region was taken over

  battle_xp_winner_bonus_factor:         2.0

  description_max_length:               1000 # character

development:
  <<: *defaults

  base_url: 'https://localhost'
  
  jabber:
    debug:     true
    host:      jabber3.wack-a-doo.com
    muc:       conference.jabber3.wack-a-doo.com
    bot_jid:   service@jabber3.wack-a-doo.com
    password:  P5Dda5eZmvCLFTw2
    name:      service
    admin_jid: shadow-dragon@jabber3.wack-a-doo.com

  base_time_factor: 1

  identity_provider_base_url: 'https://localhost/identity_provider'
  payment_provider_base_url:  'https://localhost/payment_provider'

  settlement_recalc_probability:    0.5
  character_recalc_probability:     0.5
  resource_pool_recalc_probability: 0.1
  queue_speed_recalc_probability:   0.5

  status_email_recipient: 'p@trick-fox.de'
  chargeback_email_recipient: 'p@trick-fox.de'
  sales_email_recipient: 'p@trick-fox.de'

test:
  <<: *defaults

  settlement_recalc_probability:    0
  character_recalc_probability:     0
  resource_pool_recalc_probability: 0

staging:
  <<: *defaults

  jabber:
    debug:     true
    host:      jabber3.wack-a-doo.com
    muc:       conference.jabber3.wack-a-doo.com
    bot_jid:   service@jabber3.wack-a-doo.com
    password:  P5Dda5eZmvCLFTw2
    name:      service
    admin_jid: shadow-dragon@jabber3.wack-a-doo.com
  
  base_url: 'https://test1.wack-a-doo.com'

  scope: 'wackadoo-testround3'
  
  ap_regeneration_duration: 120           # time needed to regenerate a single action point in minutes

  platinum_additional_construction_jobs : 3
  platinum_additional_training_jobs     : 3

  battle_xp_winner_bonus_factor:         3.0

  special_offer_interval:         5 #days
  special_offer_dialog_max_count: 100

production:
  <<: *defaults

  jabber:
    debug:     true
    host:      jabber4.wack-a-doo.com
    muc:       conference.jabber4.wack-a-doo.com
    bot_jid:   service@jabber4.wack-a-doo.com
    password:  P5Dda5eZmvCLFTw2
    name:      service
    admin_jid: shadow-dragon@jabber4.wack-a-doo.com
  
  scope: 'wackadoo-round3'

  default_character_name: 'WackyUser'
  identity_provider_base_url: 'https://wack-a-doo.de/identity_provider'
  
  settlement_recalc_probability:    0.2
  resource_pool_recalc_probability: 0.05
  character_recalc_probability:     0.2
  queue_speed_recalc_probability:   0.2
  
  cookie_name: 'wackadoo_r2_remember_token'  

  
  
  
  
